### ISSUE TITLE
how to convert the ArxivFormula to yolo

### ISSUE THREAD

**Issue by aspnetcs** [microsoft/ArxivFormula#2]

**Comment by KaiHu-KH** [comment]
Our dataset uses COCO-style annotations, which can be easily converted to YOLO format.

**Comment by aspnetcs** [comment]
能够给出转换代码吗？










--




At 2024-11-12 17:18:20, "Kai Hu" ***@***.***> wrote:

Our dataset uses COCO-style annotations, which can be easily converted to YOLO format.

**Comment by KaiHu-KH** [comment]
This is very simple, you can try using GPT-4 to quickly get this code. Or you can try code in this repo https://github.com/tw-yshuang/coco2yolo

**Comment by aspnetcs** [comment]
我使用 这个仓库的代码  https://github.com/tw-yshuang/coco2yolo，依据帮助文档，使用下列命令：
python coco2yolo.py -ann-path ..\ArxivFormula_examples\examples2.json -img-dir ..\ArxivFormula_examples\examples

最终出现错误：

Traceback (most recent call last):

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 308, in <module>

    main()

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1078, in main

    rv = self.invoke(ctx)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 783, in invoke

    return __callback(*args, **kwargs)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 304, in main

    Coco2Yolo(**kwargs)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 92, in __init__

    self.covert2yolo(img_info)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 226, in covert2yolo

    dw = 1.0 / img_info['width']

KeyError: 'width'




整个执行过程如下所示：

(YOLOv8-GUI-PySide6) F:\23-24-2\book\arxivmorosoft\coco2yolo-main>python coco2yolo.py -ann-path ..\ArxivFormula_examples\examples2.json -img-dir ..\ArxivFormula_examples\examples

Enter the directory that you want to save the task: ..\ArxivFormula_examples\task

loading annotations into memory...

Done (t=0.03s)

creating index...

index created!

[;36mCOCO categories[0m:

['InlineFormula', 'DisplayedFormulaLine', 'FormulaNumber', 'DisplayedFormulaBlock', 'Table', 'Figure']




Enter the categories name you wish(split: ', '): InlineFormula, DisplayedFormulaLine, FormulaNumber, DisplayedFormulaBlock, Table, Figure

['InlineFormula', 'DisplayedFormulaLine', 'FormulaNumber', 'DisplayedFormulaBlock', 'Table', 'Figure']

The total number of the data: 95

[;36mIndex Correspond Table:[0m

{'InlineFormula': 0, 'DisplayedFormulaLine': 1, 'FormulaNumber': 2, 'DisplayedFormulaBlock': 3, 'Table': 4, 'Figure': 5}

[;32mCreating symbolic links...[0m

[;33mAlready exist a directory in here, do you still want to use this directory save your task?

(Note: if yes, it will save existing & new files in the ..\ArxivFormula_examples\task)[0m [y/n]: y

[mThere has a [;31mFile Exists[0m happen, do you want to recover it?(Even at the rest of the File Exists happen)[0m [y/n]: y

[;32mSymbolic links for ..\ArxivFormula_examples\examples to ..\ArxivFormula_examples\task complete!![0m

[;32mConverting COCO format to YOLO format by task...[0m

Traceback (most recent call last):

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 308, in <module>

    main()

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1078, in main

    rv = self.invoke(ctx)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "D:\Users\Administrator.PC-202204221658\miniconda3\envs\YOLOv8-GUI-PySide6\lib\site-packages\click\core.py", line 783, in invoke

    return __callback(*args, **kwargs)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 304, in main

    Coco2Yolo(**kwargs)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 92, in __init__

    self.covert2yolo(img_info)

  File "F:\23-24-2\book\arxivmorosoft\coco2yolo-main\coco2yolo.py", line 226, in covert2yolo

    dw = 1.0 / img_info['width']

KeyError: 'width'




(YOLOv8-GUI-PySide6) F:\23-24-2\book\arxivmorosoft\coco2yolo-main>
















--




At 2024-11-12 20:03:11, "Kai Hu" ***@***.***> wrote:

This is very simple, you can try using GPT-4 to quickly get this code. Or you can try code in this repo https://github.com/tw-yshuang/coco2yolo
